# Input Data Paths
input_paths:
  charges: "Data/Charges_use.csv"
  damages: "Data/Damages_use.csv"
  endorse: "Data/Endorse_use.csv"
  primary_person: "Data/Primary_Person_use.csv"
  restrict: "Data/Restrict_use.csv"
  units: "Data/Units_use.csv"

# Output Path
output_path: "output"

# Spark Configurations
spark_configs:
  app_name: "Car Crash Analysis"
  master: "local[*]"
  log_level: "ERROR"